#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

set +e

npm run lint

if [ $? -eq 1 ]; then
  printf "${RED}ERROR: linting failed\n${NC}"
  exit 1
fi
printf "${GREEN}PASSED: linting passed\n${NC}"

exit 0;
